/*
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vouchery.sdk;

import io.vouchery.sdk.ApiException;
import org.openapitools.client.model.AnyOfRewardGenerateVoucherRewardSetDiscountRewardSetDiscountPerItemRewardGenerateProductItemRewardAddPointsRewardAssignVoucher;
import org.openapitools.client.model.Reward;
import org.openapitools.client.model.UNKNOWN_BASE_TYPE;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RewardsApi
 */
@Ignore
public class RewardsApiTest {

    private final RewardsApi api = new RewardsApi();

    
    /**
     * Create a reward
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createRewardTest() throws ApiException {
        Integer campaignId = null;
        UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE = null;
        Reward response = api.createReward(campaignId, UNKNOWN_BASE_TYPE);

        // TODO: test validations
    }
    
    /**
     * Delete a reward
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteRewardTest() throws ApiException {
        Integer id = null;
        api.deleteReward(id);

        // TODO: test validations
    }
    
    /**
     * Get a reward
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRewardTest() throws ApiException {
        Integer id = null;
        Reward response = api.getReward(id);

        // TODO: test validations
    }
    
    /**
     * Get all rewards for a campaign
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRewardsTest() throws ApiException {
        Integer campaignId = null;
        List<Reward> response = api.getRewards(campaignId);

        // TODO: test validations
    }
    
    /**
     * Update a reward
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateRewardTest() throws ApiException {
        Integer id = null;
        UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE = null;
        Reward response = api.updateReward(id, UNKNOWN_BASE_TYPE);

        // TODO: test validations
    }
    
}
