/*
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vouchery.sdk;

import io.vouchery.sdk.ApiException;
import org.openapitools.client.model.AnyOfRuleCustomerCategoryRuleCustomerMaxRedemptionsRuleCustomerPointsRuleTimeOfOrderRuleTimeframeRuleTriggersAmountRuleProductItemExists;
import org.openapitools.client.model.Rule;
import org.openapitools.client.model.UNKNOWN_BASE_TYPE;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RulesApi
 */
@Ignore
public class RulesApiTest {

    private final RulesApi api = new RulesApi();

    
    /**
     * Create a rule
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createRuleTest() throws ApiException {
        Integer campaignId = null;
        UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE = null;
        Rule response = api.createRule(campaignId, UNKNOWN_BASE_TYPE);

        // TODO: test validations
    }
    
    /**
     * Delete a rule
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteRuleTest() throws ApiException {
        Integer id = null;
        api.deleteRule(id);

        // TODO: test validations
    }
    
    /**
     * Get a rule
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRuleTest() throws ApiException {
        Integer id = null;
        Rule response = api.getRule(id);

        // TODO: test validations
    }
    
    /**
     * Get all rules for a campaign
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRulesTest() throws ApiException {
        Integer campaignId = null;
        List<Rule> response = api.getRules(campaignId);

        // TODO: test validations
    }
    
    /**
     * Update a rule
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateRuleTest() throws ApiException {
        Integer id = null;
        UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE = null;
        Rule response = api.updateRule(id, UNKNOWN_BASE_TYPE);

        // TODO: test validations
    }
    
}
