/*
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.CampaignCreatedBy;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MainCampaignChildren
 */
public class MainCampaignChildrenTest {
    private final MainCampaignChildren model = new MainCampaignChildren();

    /**
     * Model tests for MainCampaignChildren
     */
    @Test
    public void testMainCampaignChildren() {
        // TODO: test MainCampaignChildren
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'parentId'
     */
    @Test
    public void parentIdTest() {
        // TODO: test parentId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'triggersOn'
     */
    @Test
    public void triggersOnTest() {
        // TODO: test triggersOn
    }

    /**
     * Test the property 'triggerName'
     */
    @Test
    public void triggerNameTest() {
        // TODO: test triggerName
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'customerInformation'
     */
    @Test
    public void customerInformationTest() {
        // TODO: test customerInformation
    }

    /**
     * Test the property 'maxTotalBudget'
     */
    @Test
    public void maxTotalBudgetTest() {
        // TODO: test maxTotalBudget
    }

    /**
     * Test the property 'maxRedemptions'
     */
    @Test
    public void maxRedemptionsTest() {
        // TODO: test maxRedemptions
    }

    /**
     * Test the property 'minimumValue'
     */
    @Test
    public void minimumValueTest() {
        // TODO: test minimumValue
    }

    /**
     * Test the property 'maxDiscount'
     */
    @Test
    public void maxDiscountTest() {
        // TODO: test maxDiscount
    }

    /**
     * Test the property 'redemptionsCount'
     */
    @Test
    public void redemptionsCountTest() {
        // TODO: test redemptionsCount
    }

    /**
     * Test the property 'totalBudgetSpent'
     */
    @Test
    public void totalBudgetSpentTest() {
        // TODO: test totalBudgetSpent
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'currencySymbol'
     */
    @Test
    public void currencySymbolTest() {
        // TODO: test currencySymbol
    }

    /**
     * Test the property 'team'
     */
    @Test
    public void teamTest() {
        // TODO: test team
    }

    /**
     * Test the property 'channel'
     */
    @Test
    public void channelTest() {
        // TODO: test channel
    }

    /**
     * Test the property 'purpose'
     */
    @Test
    public void purposeTest() {
        // TODO: test purpose
    }

    /**
     * Test the property 'budgetCode'
     */
    @Test
    public void budgetCodeTest() {
        // TODO: test budgetCode
    }

    /**
     * Test the property 'medium'
     */
    @Test
    public void mediumTest() {
        // TODO: test medium
    }

    /**
     * Test the property 'voucherType'
     */
    @Test
    public void voucherTypeTest() {
        // TODO: test voucherType
    }

    /**
     * Test the property 'voucherCodeType'
     */
    @Test
    public void voucherCodeTypeTest() {
        // TODO: test voucherCodeType
    }

    /**
     * Test the property 'voucherRandomPartLength'
     */
    @Test
    public void voucherRandomPartLengthTest() {
        // TODO: test voucherRandomPartLength
    }

    /**
     * Test the property 'voucherPrefix'
     */
    @Test
    public void voucherPrefixTest() {
        // TODO: test voucherPrefix
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'updatedBy'
     */
    @Test
    public void updatedByTest() {
        // TODO: test updatedBy
    }

}
