/*
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.RedemptionProductItems;
import org.openapitools.client.model.RedemptionVoucher;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Redemption
 */
public class RedemptionTest {
    private final Redemption model = new Redemption();

    /**
     * Model tests for Redemption
     */
    @Test
    public void testRedemption() {
        // TODO: test Redemption
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

    /**
     * Test the property 'customerIdentifier'
     */
    @Test
    public void customerIdentifierTest() {
        // TODO: test customerIdentifier
    }

    /**
     * Test the property 'totalTransactionCost'
     */
    @Test
    public void totalTransactionCostTest() {
        // TODO: test totalTransactionCost
    }

    /**
     * Test the property 'ttl'
     */
    @Test
    public void ttlTest() {
        // TODO: test ttl
    }

    /**
     * Test the property 'grantedDiscount'
     */
    @Test
    public void grantedDiscountTest() {
        // TODO: test grantedDiscount
    }

    /**
     * Test the property 'userAgent'
     */
    @Test
    public void userAgentTest() {
        // TODO: test userAgent
    }

    /**
     * Test the property 'voucher'
     */
    @Test
    public void voucherTest() {
        // TODO: test voucher
    }

    /**
     * Test the property 'confirmed'
     */
    @Test
    public void confirmedTest() {
        // TODO: test confirmed
    }

    /**
     * Test the property 'productItems'
     */
    @Test
    public void productItemsTest() {
        // TODO: test productItems
    }

    /**
     * Test the property 'validatedAt'
     */
    @Test
    public void validatedAtTest() {
        // TODO: test validatedAt
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

    /**
     * Test the property 'confirmedAt'
     */
    @Test
    public void confirmedAtTest() {
        // TODO: test confirmedAt
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
