/*
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RuleCustomerMaxRedemptions
 */
public class RuleCustomerMaxRedemptionsTest {
    private final RuleCustomerMaxRedemptions model = new RuleCustomerMaxRedemptions();

    /**
     * Model tests for RuleCustomerMaxRedemptions
     */
    @Test
    public void testRuleCustomerMaxRedemptions() {
        // TODO: test RuleCustomerMaxRedemptions
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'maxRedemptions'
     */
    @Test
    public void maxRedemptionsTest() {
        // TODO: test maxRedemptions
    }

}
