/*
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CustomerCategories;
import org.threeten.bp.OffsetDateTime;

/**
 * Customer
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-03-09T14:06:19.023+01:00[Europe/Berlin]")
public class Customer {
  public static final String SERIALIZED_NAME_IDENTIFIER = "identifier";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER)
  private String identifier;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_LOYALTY_POINTS = "loyalty_points";
  @SerializedName(SERIALIZED_NAME_LOYALTY_POINTS)
  private Integer loyaltyPoints;

  public static final String SERIALIZED_NAME_CATEGORIES = "categories";
  @SerializedName(SERIALIZED_NAME_CATEGORIES)
  private List<CustomerCategories> categories = null;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Object metadata;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;


  public Customer identifier(String identifier) {
    
    this.identifier = identifier;
    return this;
  }

   /**
   * Valid only for creating customer. Determines unique customer identifier in your application. Can be hash, id, email or any other unique value.
   * @return identifier
  **/
  @ApiModelProperty(required = true, value = "Valid only for creating customer. Determines unique customer identifier in your application. Can be hash, id, email or any other unique value.")

  public String getIdentifier() {
    return identifier;
  }


  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }


  public Customer name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Customer full name.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Customer full name.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Customer loyaltyPoints(Integer loyaltyPoints) {
    
    this.loyaltyPoints = loyaltyPoints;
    return this;
  }

   /**
   * Number of loyalty points customer will have.
   * @return loyaltyPoints
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Number of loyalty points customer will have.")

  public Integer getLoyaltyPoints() {
    return loyaltyPoints;
  }


  public void setLoyaltyPoints(Integer loyaltyPoints) {
    this.loyaltyPoints = loyaltyPoints;
  }


  public Customer categories(List<CustomerCategories> categories) {
    
    this.categories = categories;
    return this;
  }

  public Customer addCategoriesItem(CustomerCategories categoriesItem) {
    if (this.categories == null) {
      this.categories = new ArrayList<CustomerCategories>();
    }
    this.categories.add(categoriesItem);
    return this;
  }

   /**
   * Determine how customer is related to specific category by providing related tag.
   * @return categories
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Determine how customer is related to specific category by providing related tag.")

  public List<CustomerCategories> getCategories() {
    return categories;
  }


  public void setCategories(List<CustomerCategories> categories) {
    this.categories = categories;
  }


  public Customer metadata(Object metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Any metadata, you want to store, related to customer. Key-value object, that will be displayed on customer profile page.
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Any metadata, you want to store, related to customer. Key-value object, that will be displayed on customer profile page.")

  public Object getMetadata() {
    return metadata;
  }


  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }


   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }




   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Customer customer = (Customer) o;
    return Objects.equals(this.identifier, customer.identifier) &&
        Objects.equals(this.name, customer.name) &&
        Objects.equals(this.loyaltyPoints, customer.loyaltyPoints) &&
        Objects.equals(this.categories, customer.categories) &&
        Objects.equals(this.metadata, customer.metadata) &&
        Objects.equals(this.createdAt, customer.createdAt) &&
        Objects.equals(this.updatedAt, customer.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifier, name, loyaltyPoints, categories, metadata, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Customer {\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    loyaltyPoints: ").append(toIndentedString(loyaltyPoints)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

