/*
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse200
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-03-09T14:06:19.023+01:00[Europe/Berlin]")
public class InlineResponse200 {
  public static final String SERIALIZED_NAME_VALID_ROWS_COUNT = "valid_rows_count";
  @SerializedName(SERIALIZED_NAME_VALID_ROWS_COUNT)
  private Integer validRowsCount;

  public static final String SERIALIZED_NAME_INVALID_ROWS_COUNT = "invalid_rows_count";
  @SerializedName(SERIALIZED_NAME_INVALID_ROWS_COUNT)
  private Integer invalidRowsCount;

  public static final String SERIALIZED_NAME_INVALID_ROWS = "invalid_rows";
  @SerializedName(SERIALIZED_NAME_INVALID_ROWS)
  private List<String> invalidRows = null;


  public InlineResponse200 validRowsCount(Integer validRowsCount) {
    
    this.validRowsCount = validRowsCount;
    return this;
  }

   /**
   * Get validRowsCount
   * @return validRowsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getValidRowsCount() {
    return validRowsCount;
  }


  public void setValidRowsCount(Integer validRowsCount) {
    this.validRowsCount = validRowsCount;
  }


  public InlineResponse200 invalidRowsCount(Integer invalidRowsCount) {
    
    this.invalidRowsCount = invalidRowsCount;
    return this;
  }

   /**
   * Get invalidRowsCount
   * @return invalidRowsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getInvalidRowsCount() {
    return invalidRowsCount;
  }


  public void setInvalidRowsCount(Integer invalidRowsCount) {
    this.invalidRowsCount = invalidRowsCount;
  }


  public InlineResponse200 invalidRows(List<String> invalidRows) {
    
    this.invalidRows = invalidRows;
    return this;
  }

  public InlineResponse200 addInvalidRowsItem(String invalidRowsItem) {
    if (this.invalidRows == null) {
      this.invalidRows = new ArrayList<String>();
    }
    this.invalidRows.add(invalidRowsItem);
    return this;
  }

   /**
   * Get invalidRows
   * @return invalidRows
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getInvalidRows() {
    return invalidRows;
  }


  public void setInvalidRows(List<String> invalidRows) {
    this.invalidRows = invalidRows;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.validRowsCount, inlineResponse200.validRowsCount) &&
        Objects.equals(this.invalidRowsCount, inlineResponse200.invalidRowsCount) &&
        Objects.equals(this.invalidRows, inlineResponse200.invalidRows);
  }

  @Override
  public int hashCode() {
    return Objects.hash(validRowsCount, invalidRowsCount, invalidRows);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    sb.append("    validRowsCount: ").append(toIndentedString(validRowsCount)).append("\n");
    sb.append("    invalidRowsCount: ").append(toIndentedString(invalidRowsCount)).append("\n");
    sb.append("    invalidRows: ").append(toIndentedString(invalidRows)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

