/*
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * RewardAssignVoucher
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-02-04T15:47:26.674+01:00[Europe/Berlin]")
public class RewardAssignVoucher {
  /**
   * This reward assigns existing voucher from specific subcampaign to the customer, who generated the trigger.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    ASSIGN_VOUCHER("assign_voucher");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type = TypeEnum.ASSIGN_VOUCHER;

  public static final String SERIALIZED_NAME_VOUCHER_CAMPAIGN_ID = "voucher_campaign_id";
  @SerializedName(SERIALIZED_NAME_VOUCHER_CAMPAIGN_ID)
  private BigDecimal voucherCampaignId;


  public RewardAssignVoucher type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * This reward assigns existing voucher from specific subcampaign to the customer, who generated the trigger.
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This reward assigns existing voucher from specific subcampaign to the customer, who generated the trigger.")

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  public RewardAssignVoucher voucherCampaignId(BigDecimal voucherCampaignId) {
    
    this.voucherCampaignId = voucherCampaignId;
    return this;
  }

   /**
   * Subcampaign ID, voucher is related to.
   * @return voucherCampaignId
  **/
  @ApiModelProperty(required = true, value = "Subcampaign ID, voucher is related to.")

  public BigDecimal getVoucherCampaignId() {
    return voucherCampaignId;
  }


  public void setVoucherCampaignId(BigDecimal voucherCampaignId) {
    this.voucherCampaignId = voucherCampaignId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RewardAssignVoucher rewardAssignVoucher = (RewardAssignVoucher) o;
    return Objects.equals(this.type, rewardAssignVoucher.type) &&
        Objects.equals(this.voucherCampaignId, rewardAssignVoucher.voucherCampaignId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, voucherCampaignId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RewardAssignVoucher {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    voucherCampaignId: ").append(toIndentedString(voucherCampaignId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

