/*
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * RewardGenerateVoucher
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-03-09T14:06:19.023+01:00[Europe/Berlin]")
public class RewardGenerateVoucher {
  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    GENERATEVOUCHER("GenerateVoucher");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_PREFIX = "prefix";
  @SerializedName(SERIALIZED_NAME_PREFIX)
  private String prefix;

  /**
   * What characters should the code include. Possible choices are digits, letters, and mixed.
   */
  @JsonAdapter(CodeTypeEnum.Adapter.class)
  public enum CodeTypeEnum {
    MIXED("mixed"),
    
    DIGITS("digits"),
    
    LETTERS("letters");

    private String value;

    CodeTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CodeTypeEnum fromValue(String value) {
      for (CodeTypeEnum b : CodeTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CodeTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CodeTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CodeTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CodeTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CODE_TYPE = "code_type";
  @SerializedName(SERIALIZED_NAME_CODE_TYPE)
  private CodeTypeEnum codeType;

  public static final String SERIALIZED_NAME_RANDOM_PART_LENGTH = "random_part_length";
  @SerializedName(SERIALIZED_NAME_RANDOM_PART_LENGTH)
  private BigDecimal randomPartLength;

  public static final String SERIALIZED_NAME_VOUCHER_CAMPAIGN_ID = "voucher_campaign_id";
  @SerializedName(SERIALIZED_NAME_VOUCHER_CAMPAIGN_ID)
  private BigDecimal voucherCampaignId;


  public RewardGenerateVoucher type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  public RewardGenerateVoucher title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public RewardGenerateVoucher description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public RewardGenerateVoucher prefix(String prefix) {
    
    this.prefix = prefix;
    return this;
  }

   /**
   * A prefix in all generated vouchers. Needs to be unique within a project.
   * @return prefix
  **/
  @ApiModelProperty(required = true, value = "A prefix in all generated vouchers. Needs to be unique within a project.")

  public String getPrefix() {
    return prefix;
  }


  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }


  public RewardGenerateVoucher codeType(CodeTypeEnum codeType) {
    
    this.codeType = codeType;
    return this;
  }

   /**
   * What characters should the code include. Possible choices are digits, letters, and mixed.
   * @return codeType
  **/
  @ApiModelProperty(required = true, value = "What characters should the code include. Possible choices are digits, letters, and mixed.")

  public CodeTypeEnum getCodeType() {
    return codeType;
  }


  public void setCodeType(CodeTypeEnum codeType) {
    this.codeType = codeType;
  }


  public RewardGenerateVoucher randomPartLength(BigDecimal randomPartLength) {
    
    this.randomPartLength = randomPartLength;
    return this;
  }

   /**
   * How long should the random part of the code be? Valid values are between 2 and 10.
   * minimum: 3
   * maximum: 10
   * @return randomPartLength
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "How long should the random part of the code be? Valid values are between 2 and 10.")

  public BigDecimal getRandomPartLength() {
    return randomPartLength;
  }


  public void setRandomPartLength(BigDecimal randomPartLength) {
    this.randomPartLength = randomPartLength;
  }


  public RewardGenerateVoucher voucherCampaignId(BigDecimal voucherCampaignId) {
    
    this.voucherCampaignId = voucherCampaignId;
    return this;
  }

   /**
   * Subcampaign ID, new voucher will be related to.
   * @return voucherCampaignId
  **/
  @ApiModelProperty(required = true, value = "Subcampaign ID, new voucher will be related to.")

  public BigDecimal getVoucherCampaignId() {
    return voucherCampaignId;
  }


  public void setVoucherCampaignId(BigDecimal voucherCampaignId) {
    this.voucherCampaignId = voucherCampaignId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RewardGenerateVoucher rewardGenerateVoucher = (RewardGenerateVoucher) o;
    return Objects.equals(this.type, rewardGenerateVoucher.type) &&
        Objects.equals(this.title, rewardGenerateVoucher.title) &&
        Objects.equals(this.description, rewardGenerateVoucher.description) &&
        Objects.equals(this.prefix, rewardGenerateVoucher.prefix) &&
        Objects.equals(this.codeType, rewardGenerateVoucher.codeType) &&
        Objects.equals(this.randomPartLength, rewardGenerateVoucher.randomPartLength) &&
        Objects.equals(this.voucherCampaignId, rewardGenerateVoucher.voucherCampaignId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, title, description, prefix, codeType, randomPartLength, voucherCampaignId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RewardGenerateVoucher {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    codeType: ").append(toIndentedString(codeType)).append("\n");
    sb.append("    randomPartLength: ").append(toIndentedString(randomPartLength)).append("\n");
    sb.append("    voucherCampaignId: ").append(toIndentedString(voucherCampaignId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

