/*
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.RuleProductItemExistsItemConditions;

/**
 * RuleProductItemExists
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-03-09T14:06:19.023+01:00[Europe/Berlin]")
public class RuleProductItemExists {
  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    PRODUCTITEMEXISTS("ProductItemExists");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  public static final String SERIALIZED_NAME_ITEM_CONDITIONS = "item_conditions";
  @SerializedName(SERIALIZED_NAME_ITEM_CONDITIONS)
  private List<RuleProductItemExistsItemConditions> itemConditions = new ArrayList<RuleProductItemExistsItemConditions>();


  public RuleProductItemExists type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  public RuleProductItemExists itemConditions(List<RuleProductItemExistsItemConditions> itemConditions) {
    
    this.itemConditions = itemConditions;
    return this;
  }

  public RuleProductItemExists addItemConditionsItem(RuleProductItemExistsItemConditions itemConditionsItem) {
    this.itemConditions.add(itemConditionsItem);
    return this;
  }

   /**
   * Array of item conditions, that item should fit
   * @return itemConditions
  **/
  @ApiModelProperty(required = true, value = "Array of item conditions, that item should fit")

  public List<RuleProductItemExistsItemConditions> getItemConditions() {
    return itemConditions;
  }


  public void setItemConditions(List<RuleProductItemExistsItemConditions> itemConditions) {
    this.itemConditions = itemConditions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuleProductItemExists ruleProductItemExists = (RuleProductItemExists) o;
    return Objects.equals(this.type, ruleProductItemExists.type) &&
        Objects.equals(this.itemConditions, ruleProductItemExists.itemConditions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, itemConditions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuleProductItemExists {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    itemConditions: ").append(toIndentedString(itemConditions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

